### ISSUE TITLE
p1803 - packexpr for C++23

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#11]
End tuple's tyranny.

Fight back. Our pen is mightier than the compiler's sword.

**Comment by ThePhD** [comment]
Piggyback off [p1306](https://wg21.link/p1306).

**Comment by ThePhD** [comment]
p1306 is going into C++20. Prepare for a post-Kona paper about this.

**Comment by slurps-mad-rips** [comment]
Is this any different from the old `value_at` paper from Sean Middleditch?

**Comment by ThePhD** [comment]
Probably not? Except it shouldn't be a library function.

**Comment by ThePhD** [comment]
> http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3761.html

Yeah no this is a bad take, mostly because it incurs the same overhead. The point is to make the compiler do the work: a library function can be done by the user, but incurs the terrible overhead we don't want to begin with. We want the <get-expr> done behind-the-scenes in p1306 to be standarized.

**Comment by Marqin** [comment]
👍 Not having this in C++ gave me a lot of headache last week...

**Comment by ThePhD** [comment]
Has no paper number now because un-submitted papers went straight to hell.

Still, we should ask for p1420 back...

**Comment by ThePhD** [comment]
Paper number is now 1803 (empty placeholder paper at this time): https://thephd.github.io/vendor/future_cxx/papers/d1803.html

**Comment by Morwenn** [comment]
magic_get probably isn't the best name considering that there is already an interesting library with that name which does something else :thinking:

**Comment by ThePhD** [comment]
`packexpr` it is: https://thephd.github.io/vendor/future_cxx/papers/d1803.html

**Comment by ThePhD** [comment]
This paper is hella dead, and may only be conditionally revived if Barry Revzin -- champion of the people -- is defeated: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1858r0.html

**Comment by h-vetinari** [comment]
I was reminded of this by seeing Sean Bax's [keynote](https://www.youtube.com/watch?v=15j4bkipuAg) recently, which does this and _oh-so-much_ more (and given the snippets before/after he presents, it's unsurprising that people are clamouring to have that sort of power). Also notable [quote](https://www.youtube.com/watch?v=15j4bkipuAg&t=290s) IMO:
> The language's standard library is written by the language's most skilled programmers, usually. And the standard library code _should_ be an advertisement for a language, but in C++, it's a warning. 

Not that you're not aware of Circle's capabilities, but since that paper is still on your page and has an issue here, it's funny (and impressive) to me that you had a very good hand in picking some of the most pertinent (but also hardest) problems already "early on".

**Comment by ThePhD** [comment]
I have a knack for getting into trouble, apparently.
